#!/bin/bash

# http://docs.opencv.org/doc/tutorials/introduction/android_binary_package/dev_with_OCV_on_Android.html
# http://code.opencv.org/projects/opencv/wiki/Building_OpenCV4Android_from_trunk
# https://github.com/Itseez/opencv

export ANDROID_NDK=~/NVPACK/android-ndk-r10e
export ANDROID_STANDALONE_TOOLCHAIN=~/NVPACK/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8
export ANDROID_SDK=~/NVPACK/android-sdk-linux
export ANDROID_SDK_TOOLS_PATH=~/NVPACK/android-sdk-linux/tools

cd ./platforms

sh ./scripts/cmake_android_arm_sm53.sh

#cmake -DBUILD_SHARED_LIBS=OFF ..

cd build_android_arm_sm53
make VERBOSE=1 -j8
make install
